### ISSUE TITLE
check login status

### ISSUE THREAD

**Issue by JhChoy** [HAECHI-LABS/henesis-cli#60]
Current Behavior:
Assume already logged in.
```
$ henesis login
email:
```

Expected Behavior:
```
$ henesis login
You already logged in with jay@haechi.io
```

**Comment by zero1ne-dev** [comment]
Resolved
<img width="470" alt="스크린샷 2019-08-26 오후 6 57 05" src="https://user-images.githubusercontent.com/1378925/63682626-55ce9500-c833-11e9-833b-4c9c9cb5f372.png">
